Check for all possible remote source methods
transcend-io/terragrunt-atlantis-config pull request #180
Opened 2021-11-10 22:36 UTC by henworth

# Pull Request

## Related Github Issues
- #172 

## Description

Refactor the remote module source path check to encompass all possible types. Use [go-getter](https://github.com/hashicorp/go-getter) to detect the source path, which normalizes the string into a format that can be checked by regex to cover any remote protocol prefix. This helps ensure we support the same source methods that Terraform (and by extension, Terragrunt) do.

Expand the test suite to cover all source methods as documented in the [Terraform docs](https://www.terraform.io/docs/language/modules/sources.html).

## Security Implications

- _[none]_

## System Availability

- _[none]_

2021-11-10 23:05 UTC, john-delivuk commented
Didn't realize @henworth opened this. #181 is redundant, so let me know if you want to close it in favor. That being said, I think it would be wise to find local paths, rather than finding and excluding remote. Otherwise each new source would require an update.

2021-11-10 23:33 UTC, henworth commented
I don't disagree. I think if combine our approaches we'll have a good solution. If we normalize the string using go-getter, then check that for local prefixes that seems like a good way to ensure all bases are covered.

2021-11-11 00:07 UTC, john-delivuk commented
That sounds great. I wasn't aware of getter, but looks like that will do all the heavy lifting for us. I'll close my PR as you had simnifically better test coverage.

2021-11-11 01:26 UTC, dmattia commented
That sounds good to me as well! Please @ me when it is ready to review 😄

2021-11-11 01:57 UTC, henworth commented
@dmattia I think we're looking good now. Turns out the check is super easy, all local paths will begin with `file:///` once parsed.

2021-11-11 02:51 UTC, dmattia approved these changes

2021-11-11 02:53 UTC, dmattia requested changes
@henworth It looks like the tests are failing on Windows, but otherwise this looks fantastic. I'm guessing they start with something other than `file:///` on windows, but I'm not totally sure

2021-11-11 13:38 UTC, henworth commented
@dmattia I sorted out the Windows issue. Looks like a local path could either start with `file://` or a drive letter. Not sure on the rain for the distinction (might be due to  absolute paths or the // submodule indicator), but it works now!

2021-11-11 15:22 UTC, dmattia approved these changes

2021-11-11 15:22 UTC, merged

2021-11-11 16:03 UTC, dmattia commented
This should be released in v1.11.0: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.11.0

Thank you very much!